# Generated by Django 3.2.7 on 2022-03-26 04:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work', models.CharField(default='', max_length=50)),
                ('studiesrelated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=datetime.datetime.now)),
                ('desc', models.TextField(default='', max_length=100)),
                ('freq', models.IntegerField(default=0)),
                ('Work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TodoApp.todo')),
            ],
        ),
    ]
