# Generated by Django 3.2.7 on 2022-03-28 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='workdetails',
            name='Work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TodoApp.todo'),
        ),
    ]
